/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript
 * from https://github.com/elyra-ai/pipeline-schemas/blob/main/common-canvas/expression/function-list-v3-schema.json
 * It has been modified by hand, so run a diff if you need to update it.
 */

import { ResourceDefinition } from './uihints-v3.model';

/**
 * Watson Data Platform Expression Builder Function List Schema for the Common Properties editor
 */
export interface ExpressionBuilderFunctionListSchema {
  /**
   * Array of categories of functions
   *
   * @minItems 0
   */
  function_categories: FunctionCategoriesDef[];
  /**
   * Array of refs to functions that will be displayed as operators.
   *
   * @minItems 1
   */
  operator_refs?: [string, ...string[]];
  /**
   * Array of function information
   *
   * @minItems 1
   */
  function_info: [FunctionDef, ...FunctionDef[]];
  [k: string]: unknown;
}
/**
 * Definition of a information about a function
 */
export interface FunctionCategoriesDef {
  /**
   * Unique string to reference this category
   */
  id?: string;
  /**
   * External name of category
   */
  label: ResourceDefinition;
  /**
   * Array of function ids that are part of this fuction category
   *
   * @minItems 1
   */
  function_refs: [string, ...string[]];
}
/**
 * Definition of a information about a function
 */
export interface FunctionDef {
  /**
   * Unique string to reference this function
   */
  id: string;
  /**
   * User-readable name of function
   */
  label: ResourceDefinition;
  /**
   * Array of parameter information
   *
   * @minItems 0
   */
  parameters?: FunctionParameterDef[];
  /**
   * Translatable data type name of what is returned from the function. If this is not provided, default to return_type
   */
  return_type_label?: ResourceDefinition;
  /**
   * The data type name of what is returned from the function.
   */
  return_type: string;
  /**
   * The help text for the function.
   */
  description?: ResourceDefinition;
}
/**
 * Definition of a information about a functions parameters.
 */
export interface FunctionParameterDef {
  /**
   * User-readable name of parameter
   */
  label: ResourceDefinition;
  /**
   * The type of the parameter.
   */
  type?: string;
  [k: string]: unknown;
}
