/*
 * Copyright 2017-2024 Elyra Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { NodeTypeDef } from './pipeline-flow-v3';

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript
 * from https://github.com/elyra-ai/pipeline-schemas/blob/main/common-canvas/palette/palette-v3-schema.json
 * after removing broken $ref URL's.
 * It has been modified by hand, so run a diff if you need to update it.
 */

/**
 * Common Canvas palette schema
 */
export interface HttpsApiDataplatformIbmComSchemasCommonCanvasPalettePaletteV3SchemaJson {
  /**
   * Palette schema version
   */
  version?: '3.0';
  /**
   * Array of palette categories
   *
   * @minItems 0
   */
  categories?: CategoryDef[];
}
/**
 * Palette Category
 */
export interface CategoryDef {
  /**
   * ID of the category
   */
  id: string;
  /**
   * Category label
   */
  label: string;
  /**
   * Category description
   */
  description?: string;
  /**
   * Boolean to indicate if the category is open (true) or not (false).
   */
  is_open?: boolean;
  /**
   * When set to a non-empty string and node_types is empty, is used to indicate that no nodes exist
   */
  empty_text?: string;
  /**
   * When set to a non-empty string, causes a loading indicator to appear with this text as a label
   */
  loading_text?: string;
  /**
   * Encoded image or image reference for the category
   */
  image?: string;
  /**
   * Array of pipeline node types
   *
   * @minItems 0
   */
  node_types?: NodeTypeDef[];
}
