/*
 * Copyright 2017-2024 Elyra Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript
 * from https://github.com/elyra-ai/pipeline-schemas/blob/main/common-canvas/parameter-defs/parameter-defs-v3-schema.json
 * It has been modified by hand, so run a diff if you need to update it.
 */

import { ConditionsDefinition } from './conditions-v3.model';
import {
  ComplexTypeDefinition,
  ParameterDefinition,
} from './operator-v3.model';
import { WDPUIHintsSchema } from './uihints-v3.model';

/**
 * Watson Data Platform Property Definition Schema for the Common Properties editor
 */
export interface PropertyDefinitionsSchema {
  titleDefinition?: {
    title?: string;
    /**
     * True if the title can be edited. False if the title should be readonly.
     */
    editable?: boolean;
    [k: string]: unknown;
  };
  /**
   * Current parameter set upon input. Keys are parameter names, values are their values.
   */
  current_parameters?: {
    [k: string]: unknown;
  };
  /**
   * Current UI only parameter set upon input. Keys are parameter names, values are their values.
   */
  current_ui_parameters?: {
    [k: string]: unknown;
  };
  parameters?: ParameterDefinition[];
  complex_types?: ComplexTypeDefinition[];
  uihints?: WDPUIHintsSchema;
  conditions?: ConditionsDefinition[];
  dataset_metadata?:
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }[];
  /**
   * Map of string resources.
   */
  resources?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
