/*
 * Copyright 2017-2024 Elyra Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript
 * from https://github.com/elyra-ai/pipeline-schemas/blob/main/common-pipeline/parameters/parameters-v3-schema.json
 * It has been modified by hand, so run a diff if you need to update it.
 */

/**
 * Parameters schema for pipelines in the Watson Data Platform
 */
export interface WatsonDataPlatformPipelineParametersSchema {
  /**
   * Refers to the JSON schema used to validate documents of this type
   */
  json_schema?: 'https://api.dataplatform.ibm.com/schemas/common-pipeline/parameters/parameters-v3-schema.json';
  /**
   * @minItems 0
   */
  parameters: ParamPropertyDef[];
  [k: string]: unknown;
}
/**
 * The parameter definition.
 */
export interface ParamPropertyDef {
  /**
   * The name of the parameter.
   */
  name: string;
  /**
   * The description of the parameter.
   */
  description?: string;
  /**
   * The parameter type. Each product manages its own list of parameter type. The parameter type should be an enum list ideally. As schema is common to all products, use string instead.
   */
  type: string;
  /**
   * The parameter subtype.
   */
  subtype?: string;
  /**
   * The literal default value to replace at runtime.
   */
  value?: {
    [k: string]: unknown;
  };
  /**
   * Valid values.
   */
  valid_values?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
