#
# Copyright 2017-2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
  ignore: './src/**/_sprites.scss'
rules:
  clean-import-paths: 0
  no-css-comments: 0
  no-color-literals: 0
  hex-length: 0
  no-ids: 0
  no-qualifying-elements: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  single-line-per-selector: 0
  empty-line-between-blocks: 0
  class-name-format: 0
  property-sort-order: 0
  no-duplicate-properties:
    - 1
    -
      exclude:
        - background
  no-vendor-prefixes:
    - 1
    -
      'excluded-identifiers':
        - 'webkit'
        - 'moz'
  indentation:
    - 2
    -
      size: 'tab'
  quotes:
    - 2
    -
      style: double
  hex-notation:
    - 2
    -
      style: uppercase
  nesting-depth:
    - 1
    - max-depth: 5
  leading-zero:
    - 2
    - include: true
